linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused

linters-settings:
  revive:
    rules:
      - name: cyclomatic
        arguments: [10]

run:
  timeout: 5m